Fix missing key 'requirements' in meta file
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.8.2/libexec/bin/ansible-galaxy", line 954, in <module>
    main()
  File "/usr/local/Cellar/ansible/1.8.2/libexec/bin/ansible-galaxy", line 948, in main
    fn(args, options, parser)
  File "/usr/local/Cellar/ansible/1.8.2/libexec/bin/ansible-galaxy", line 842, in execute_install
    role_dependencies = role_data['dependencies']
KeyError: 'dependencies'